---
title: "Week 3 Data"
author: "RWW"
bibliography: "bibliography.bib"
nocite: |
     @*
format: 
   html:
     self-contained: true
     self-contained-math: true
     code-fold: true
     code-copy: hover
     code-block-border-left: true
     df-print: paged
     embed-resources: true
     fig-format: retina
     footnotes-hover: true
     html-math-method: katex
     mainfont: Playfair Display
     toc: true
     toc-title: Navigation
     theme: simplex
---

## Load the Data

```{r}
load(url("https://github.com/robertwwalker/DADMStuff/raw/master/Week3Data.RData"))
```

## View the Data

The magic of datatable and the `DT` library's `datatable` command.

```{r}
library(DT)
```

### Disability Expenditures

#### Without NoExcel

```{r}
datatable(DisabilityExp)
```

#### NoExcel

```{r}
library(DT)
datatable(DisabilityExp.NoExcel)
```


## UCB Admissions

```{r}
library(DT)
UCBAdmit$Dept <- as.factor(UCBAdmit$Dept) 
datatable(UCBAdmit)
```

## Bonds

```{r}
datatable(Bonds)
```

## FastFood

```{r}
datatable(FastFood)
```

## CEO Compensation

```{r}
datatable(CEOComp)
```

# References

```{r}
knitr::write_bib(names(sessionInfo()$otherPkgs), file="bibliography.bib")
```
